apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
    spec:
      containers:
        - name: mycontainer
          image: wil42/playground:v1
